### ISSUE TITLE
Present throws SerializationException

### ISSUE THREAD

**Issue by mlacker** [mlacker/RoeHack#4]
![image](https://user-images.githubusercontent.com/9708411/77799685-43aa2300-70b0-11ea-9fc6-04ab160e088b.png)
i got SerializationException, cause by SharpDX.SharpDXException can not be serialization. maybe should be use presentHook.Target ?
https://github.com/mlacker/RoeHack/blob/df6454cbb97839507523d2cb7556a7e8792545f8/Library/DirectXHooker/DriectX12Hooker.cs#L79

**Comment by PourrezJ** [comment]
Is possible, try this:
`        public SharpDX.Result PresentHook(IntPtr swapChainPtr, int syncInterval, PresentFlags flags)
        {
            if (swapChain == null)
            {
                swapChain = SwapChain3.FromPointer<SwapChain3>(swapChainPtr);
            }

            return hookPresent.Target(swapChainPtr, syncInterval, flags);
        }`
